- hosts: default
  tasks:
     - name: Install needed packages
       become: yes
       yum: name=grubby,docker,docker-compose,unzip,git,time,bc state=installed
     - name: Change Cgroup
       become: yes
       shell: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
     - name: Add User to docker group
       become: yes
       shell: gpasswd -a gepard docker
     - name: set max_map_count
       become: yes
       lineinfile:
         path: /etc/sysctl.conf
         line: vm.max_map_count=300000
     - name: Enable Docker Daemon
       become: yes
       systemd:
         name: docker
         enabled: yes
     - name: Reboot needed
       become: yes
       reboot:
     - name: Copy Elastic-APM
       copy:
         src: /home/hwirnsberger/NAS/Gepardec/packer-vms/troubleshooting_vm/bin/elastic-apm/
         dest: "{{ ansible_env.HOME }}/elastic-apm/"
     - name: Start Elastic APM
       docker_compose:
         project_src: "{{ ansible_env.HOME }}/elastic-apm/"
     - name: create needed dirs
       loop:
         - bin/
         - java/
       file:
         state: directory
         path: "{{ ansible_env.HOME }}/{{ item }}"
     - name: Copy and unpack IBM JDK
       unarchive:
         src: /home/hwirnsberger/NAS/Gepardec/packer-vms/troubleshooting_vm/bin/java/ibm-java-x86_64-80.zip
         dest: "{{ ansible_env.HOME }}/java/"
     - name: Copy and unpack Oracle JDK
       unarchive:
         src: /home/hwirnsberger/NAS/Gepardec/packer-vms/troubleshooting_vm/bin/java/jdk1.8.0_201-amd64.zip
         dest: "{{ ansible_env.HOME }}/java/"
     - name: set default java
       lineinfile:
         path: "{{ ansible_env.HOME }}/.bashrc"
         line: PATH="{{ ansible_env.HOME }}/java/jdk1.8.0_201-amd64/bin/:$PATH"
     - name: Copy JBoss
       copy:
         src: /home/hwirnsberger/NAS/Gepardec/packer-vms/troubleshooting_vm/bin/jboss/jboss-eap-7.2.2.zip
         dest: "{{ ansible_env.HOME }}/Downloads/"
     - name: Copy JBoss RC config
       copy:
         src: /home/hwirnsberger/NAS/Gepardec/packer-vms/troubleshooting_vm/bin/jboss/eap7rc
         dest: "{{ ansible_env.HOME }}/.eap7rc"
     - name: Copy JBoss Tools
       copy:
         src: /home/hwirnsberger/NAS/Gepardec/packer-vms/troubleshooting_vm/bin/jboss/eap7
         dest: "{{ ansible_env.HOME }}/bin/eap7"
         mode: preserve
     - name: Copy MAT
       unarchive:
         src: /home/hwirnsberger/NAS/Gepardec/packer-vms/troubleshooting_vm/bin/mat.zip
         dest: "{{ ansible_env.HOME }}/"
     - name: Clone Troubleshooting Workshop
       git:
         repo: https://github.com/Gepardec/TroubleshootingWorkshop.git
         dest: "{{ ansible_env.HOME }}/TroubleshootingWorkshop"
     - name: Add alias
       loop:
         - alias cdl="cd {{ ansible_env.HOME }}/jboss-eap-7.2.2/standalone/log/"
         - alias cdc="cd {{ ansible_env.HOME }}/jboss-eap-7.2.2/standalone/configuration/"
         - alias cdd="cd {{ ansible_env.HOME }}/jboss-eap-7.2.2/standalone/deployments/"
         - alias cdb="cd {{ ansible_env.HOME }}/jboss-eap-7.2.2/bin/"
       lineinfile:
         path: "{{ ansible_env.HOME }}/.bashrc"
         line: "{{ item }}"
