- hosts: default
  gather_facts: false
  tasks:
     - name: Install needed packages
       become: yes
       yum: name=grubby,docker,docker-compose,unzip,git,time,bc state=installed
     - name: Change Cgroup
       become: yes
       shell: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
     - name: Add User to docker group
       become: yes
       shell: gpasswd -a gepard docker
     - name: set max_map_count
       become: yes
       lineinfile:
         path: /etc/sysctl.conf
         line: vm.max_map_count=300000
     - name: Enable Docker Daemon
       become: yes
       systemd:
         name: docker
         enabled: yes
     - name: Reboot needed
       become: yes
       reboot:
     - name: Copy Elastic-APM
       copy:
         src: bin/elastic-apm/
         dest: /home/gepard/elastic-apm/
     - name: Start Elastic APM
       docker_compose:
         project_src: /home/gepard/elastic-apm/
     - name: create needed dirs
       loop:
         - bin/
         - java/
       file:
         state: directory
         path: "/home/gepard/{{ item }}"
     - name: Copy and unpack IBM JDK
       unarchive:
         src: bin/java/ibm-java-x86_64-80.zip
         dest: /home/gepard/java/
     - name: Copy and unpack Oracle JDK
       unarchive:
         src: bin/java/jdk1.8.0_201-amd64.zip
         dest: /home/gepard/java/
     - name: set default java
       lineinfile:
         path: /home/gepard/.bashrc
         line: PATH="/home/gepard/java/jdk1.8.0_201-amd64/bin/:$PATH"
     - name: Copy JBoss
       copy:
         src: bin/jboss/jboss-eap-7.2.2.zip
         dest: /home/gepard/Downloads/
     - name: Copy JBoss RC config
       copy:
         src: bin/jboss/eap7rc
         dest: /home/gepard/.eap7rc
     - name: Copy JBoss Tools
       copy:
         src: bin/jboss/eap7
         dest: /home/gepard/bin/eap7
         mode: preserve
     - name: Copy MAT
       unarchive:
         src: bin/mat.zip
         dest: /home/gepard/
     - name: Clone Troubleshooting Workshop
       git:
         repo: https://github.com/Gepardec/TroubleshootingWorkshop.git
         dest: /home/gepard/TroubleshootingWorkshop
     - name: Add alias
       loop:
         - alias cdl="cd /home/gepard/jboss-eap-7.2.2/standalone/log/"
         - alias cdc="cd /home/gepard/jboss-eap-7.2.2/standalone/configuration/"
         - alias cdd="cd /home/gepard/jboss-eap-7.2.2/standalone/deployments/"
         - alias cdb="cd /home/gepard/jboss-eap-7.2.2/bin/"
       lineinfile:
         path: /home/gepard/.bashrc
         line: "{{ item }}"
